name: Cordova Android CD

on:
    push:
        branches: [next]

jobs:
    build-apk-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build APK using setup-cordova
              uses: oxr463/setup-cordova@0.0.3
              with:
                  exec: |
                      npm i && \
                      npm run build && \
                      cd app && \
                      cordova platform add android && \
                      cordova build --no-telemetry && \
                      cd .. && mkdir release && \
                      cp "$(find . -name '*.apk')" . && \
                      mv app-debug.apk release/CashPlot.apk && \
                      cd public && \
                      tar -czf ../release/CashPlot.tar.gz .
            - name: Upload APK build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: android-build
                  path: ./release/CashPlot.apk
            - name: Upload web build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: web-build
                  path: ./release/CashPlot.tar.gz
            - name: Publish GitHub release on create tag
              uses: fnkr/github-action-ghr@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GHR_PATH: ./release
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
