name: Node.js CD
on:
  push:
    branches: [master]
jobs:

  publish:
    name: Publish to website
    runs-on: ubuntu-latest
    steps:
    - name: SSH into server, fetch changes and build
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: |
          cd /var/www/cuiter.me-cashplot
          git pull
          npm i
          npm run build
